In [1]:
from tdc.multi_pred import DDI
import pandas as pd
from pathlib import Path

print("Imports successful!")

Imports successful!

In [2]:
DATA_PATH = Path("../data/raw/tdc")
DATA_PATH.mkdir(parents=True, exist_ok=True)

print("Data will be stored in:", DATA_PATH.resolve())

Data will be stored in: /Users/apple/Documents/SIH2026/Prescription_safety_graph/data/raw/tdc

In [3]:
drugbank_data = DDI(
    name="DrugBank",
    path=str(DATA_PATH)
)

print("DrugBank DDI dataset object created successfully!")

Downloading...
100%|██████████| 44.4M/44.4M [00:04<00:00, 8.99MiB/s]
Loading...
Done!

DrugBank DDI dataset object created successfully!

In [4]:
drugbank_df = drugbank_data.get_data()

print("Dataset loaded successfully!")
print("Shape:", drugbank_df.shape)

Dataset loaded successfully!
Shape: (191808, 5)

In [5]:
drugbank_df.head()

,Drug1_ID,Drug1,Drug2_ID,Drug2,Y
0,DB04571,CC1=CC2=CC3=C(OC(=O)C=C3C)C(C)=C2O1,DB00460,COC(=O)CCC1=C2NC(\C=C3/N=C(/C=C4\N\C(=C/C5=N/C...,1
1,DB00855,NCC(=O)CCC(O)=O,DB00460,COC(=O)CCC1=C2NC(\C=C3/N=C(/C=C4\N\C(=C/C5=N/C...,1
2,DB09536,O=[Ti]=O,DB00460,COC(=O)CCC1=C2NC(\C=C3/N=C(/C=C4\N\C(=C/C5=N/C...,1
3,DB01600,CC(C(O)=O)C1=CC=C(S1)C(=O)C1=CC=CC=C1,DB00460,COC(=O)CCC1=C2NC(\C=C3/N=C(/C=C4\N\C(=C/C5=N/C...,1
4,DB09000,CC(CN(C)C)CN1C2=CC=CC=C2SC2=C1C=C(C=C2)C#N,DB00460,COC(=O)CCC1=C2NC(\C=C3/N=C(/C=C4\N\C(=C/C5=N/C...,1

In [6]:
print("Columns:")
print(drugbank_df.columns.tolist())

print("\nData types:")
print(drugbank_df.dtypes)

print("\nMissing values:")
print(drugbank_df.isnull().sum())

Columns:
['Drug1_ID', 'Drug1', 'Drug2_ID', 'Drug2', 'Y']

Data types:
Drug1_ID    object
Drug1       object
Drug2_ID    object
Drug2       object
Y            int64
dtype: object

Missing values:
Drug1_ID    0
Drug1       0
Drug2_ID    0
Drug2       0
Y           0
dtype: int64

In [7]:
drugbank_df["Y"].value_counts(dropna=False)

Y
49    60751
47    34360
73    23779
75     9470
60     8397
      ...
28       11
1        11
52       10
26        7
42        6
Name: count, Length: 86, dtype: int64

In [8]:
drugbank_df["Y"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86])

In [9]:
exact_duplicates = drugbank_df.duplicated().sum()
print("Exact duplicate rows:", exact_duplicates)

Exact duplicate rows: 0

In [10]:
pair_duplicates = drugbank_df.duplicated(
    subset=["Drug1_ID", "Drug2_ID"],
    keep=False
).sum()

print("Rows belonging to repeated directed pairs:", pair_duplicates)

Rows belonging to repeated directed pairs: 578

In [11]:
repeated_pairs = drugbank_df[
    drugbank_df.duplicated(
        subset=["Drug1_ID", "Drug2_ID"],
        keep=False
    )
].sort_values(
    ["Drug1_ID", "Drug2_ID", "Y"]
)

repeated_pairs.head(20)

,Drug1_ID,Drug1,Drug2_ID,Drug2,Y
61461,DB00182,CC(N)CC1=CC=CC=C1,DB01156,CC(NC(C)(C)C)C(=O)C1=CC(Cl)=CC=C1,47
107159,DB00182,CC(N)CC1=CC=CC=C1,DB01156,CC(NC(C)(C)C)C(=O)C1=CC(Cl)=CC=C1,49
21064,DB00199,CC[C@H]1OC(=O)[C@H](C)[C@@H](O[C@H]2C[C@@](C)(...,DB00834,[H][C@@]12CC[C@@](O)(C#CC)[C@@]1(C)C[C@H](C1=C...,20
162536,DB00199,CC[C@H]1OC(=O)[C@H](C)[C@@H](O[C@H]2C[C@@](C)(...,DB00834,[H][C@@]12CC[C@@](O)(C#CC)[C@@]1(C)C[C@H](C1=C...,73
20901,DB00207,CC[C@H]1OC(=O)[C@H](C)[C@@H](O[C@H]2C[C@@](C)(...,DB00834,[H][C@@]12CC[C@@](O)(C#CC)[C@@]1(C)C[C@H](C1=C...,20
165094,DB00207,CC[C@H]1OC(=O)[C@H](C)[C@@H](O[C@H]2C[C@@](C)(...,DB00834,[H][C@@]12CC[C@@](O)(C#CC)[C@@]1(C)C[C@H](C1=C...,73
2722,DB00238,CC1=C2NC(=O)C3=C(N=CC=C3)N(C3CC3)C2=NC=C1,DB00401,COC(=O)C1=C(C)NC(C)=C(C1C1=CC=CC=C1[N+]([O-])=...,4
188195,DB00238,CC1=C2NC(=O)C3=C(N=CC=C3)N(C3CC3)C2=NC=C1,DB00401,COC(=O)C1=C(C)NC(C)=C(C1C1=CC=CC=C1[N+]([O-])=...,75
2909,DB00238,CC1=C2NC(=O)C3=C(N=CC=C3)N(C3CC3)C2=NC=C1,DB00541,[H][C@@]12N3CC[C@@]11C4=C(C=C(OC)C(=C4)[C@]4(C...,4
188203,DB00238,CC1=C2NC(=O)C3=C(N=CC=C3)N(C3CC3)C2=NC=C1,DB00541,[H][C@@]12N3CC[C@@]11C4=C(C=C(OC)C(=C4)[C@]4(C...,75
4432,DB00238,CC1=C2NC(=O)C3=C(N=CC=C3)N(C3CC3)C2=NC=C1,DB01115,COC(=O)C1=C(C)NC(C)=C(C1C1=CC=CC=C1[N+]([O-])=...,4
183756,DB00238,CC1=C2NC(=O)C3=C(N=CC=C3)N(C3CC3)C2=NC=C1,DB01115,COC(=O)C1=C(C)NC(C)=C(C1C1=CC=CC=C1[N+]([O-])=...,75
12629,DB00238,CC1=C2NC(=O)C3=C(N=CC=C3)N(C3CC3)C2=NC=C1,DB06697,[H][C@@]12CC[C@@H](C)[C@]3([H])CC[C@@]4(C)OO[C...,11
183941,DB00238,CC1=C2NC(=O)C3=C(N=CC=C3)N(C3CC3)C2=NC=C1,DB06697,[H][C@@]12CC[C@@H](C)[C@]3([H])CC[C@@]4(C)OO[C...,75
2600,DB00238,CC1=C2NC(=O)C3=C(N=CC=C3)N(C3CC3)C2=NC=C1,DB06708,CCCCN(CCCC)CC(O)C1=C2C(=CC(Cl)=C1)\C(=C/C1=CC=...,4
186994,DB00238,CC1=C2NC(=O)C3=C(N=CC=C3)N(C3CC3)C2=NC=C1,DB06708,CCCCN(CCCC)CC(O)C1=C2C(=CC(Cl)=C1)\C(=C/C1=CC=...,75
160745,DB00252,O=C1NC(=O)C(N1)(C1=CC=CC=C1)C1=CC=CC=C1,DB00243,COC1=CC=CC=C1OCC(O)CN1CCN(CC(=O)NC2=C(C)C=CC=C...,73
179139,DB00252,O=C1NC(=O)C(N1)(C1=CC=CC=C1)C1=CC=CC=C1,DB00243,COC1=CC=CC=C1OCC(O)CN1CCN(CC(=O)NC2=C(C)C=CC=C...,75
165330,DB00252,O=C1NC(=O)C(N1)(C1=CC=CC=C1)C1=CC=CC=C1,DB00401,COC(=O)C1=C(C)NC(C)=C(C1C1=CC=CC=C1[N+]([O-])=...,73
186206,DB00252,O=C1NC(=O)C(N1)(C1=CC=CC=C1)C1=CC=CC=C1,DB00401,COC(=O)C1=C(C)NC(C)=C(C1C1=CC=CC=C1[N+]([O-])=...,75

In [12]:
pair_summary = (
    repeated_pairs
    .groupby(["Drug1_ID", "Drug2_ID"])
    .agg(
        interaction_types=("Y", list),
        num_interaction_types=("Y", "nunique"),
        total_records=("Y", "size")
    )
    .reset_index()
)

pair_summary.head(20)

   Drug1_ID Drug2_ID interaction_types  num_interaction_types  total_records
0   DB00182  DB01156          [47, 49]                      2              2
1   DB00199  DB00834          [20, 73]                      2              2
2   DB00207  DB00834          [20, 73]                      2              2
3   DB00238  DB00401           [4, 75]                      2              2
4   DB00238  DB00541           [4, 75]                      2              2
5   DB00238  DB01115           [4, 75]                      2              2
6   DB00238  DB06697          [11, 75]                      2              2
7   DB00238  DB06708           [4, 75]                      2              2
8   DB00252  DB00243          [73, 75]                      2              2
9   DB00252  DB00401          [73, 75]                      2              2
10  DB00252  DB00997           [4, 75]                      2              2
11  DB00252  DB01115          [73, 75]                      2              2
12  DB00252  DB06697          [11, 73]                      2              2
13  DB00252  DB06708           [4, 75]                      2              2
14  DB00252  DB09123          [70, 75]                      2              2
15  DB00263  DB00834          [20, 73]                      2              2
16  DB00312  DB00243           [4, 75]                      2              2
17  DB00312  DB00401           [4, 75]                      2              2
18  DB00312  DB00541           [4, 75]                      2              2
19  DB00312  DB00997           [4, 75]                      2              2

In [13]:
duplicate_relationships = drugbank_df.duplicated(
    subset=["Drug1_ID", "Drug2_ID", "Y"]
).sum()

print("Duplicate drug-pair + interaction-type records:", duplicate_relationships)

Duplicate drug-pair + interaction-type records: 0

In [14]:
pair_set = set(
    zip(
        drugbank_df["Drug1_ID"],
        drugbank_df["Drug2_ID"]
    )
)

reverse_pair_count = sum(
    1
    for drug1, drug2 in pair_set
    if (drug2, drug1) in pair_set
)

print("Directed pairs having a reverse counterpart:", reverse_pair_count)
print("Total unique directed pairs:", len(pair_set))

Directed pairs having a reverse counterpart: 234
Total unique directed pairs: 191519

In [15]:
unique_drugs = set(drugbank_df["Drug1_ID"]) | set(drugbank_df["Drug2_ID"])

print("Unique drugs:", len(unique_drugs))

Unique drugs: 1706

In [16]:
drug1_map = (
    drugbank_df.groupby("Drug1_ID")["Drug1"]
    .nunique()
)

drug2_map = (
    drugbank_df.groupby("Drug2_ID")["Drug2"]
    .nunique()
)

print("Drug1 IDs with multiple structures:", (drug1_map > 1).sum())
print("Drug2 IDs with multiple structures:", (drug2_map > 1).sum())

Drug1 IDs with multiple structures: 0
Drug2 IDs with multiple structures: 0

In [18]:
import os

print("Current working directory:")
print(os.getcwd())

Current working directory:
/Users/apple/Documents/SIH2026/Prescription_safety_graph/notebooks

In [19]:
from pathlib import Path

twosides_path = Path("../data/raw/twosides")
twosides_path.mkdir(parents=True, exist_ok=True)

print("Download path:", twosides_path.resolve())

Download path: /Users/apple/Documents/SIH2026/Prescription_safety_graph/data/raw/twosides

In [20]:
from tdc.multi_pred import DDI

twosides_data = DDI(
    name="TWOSIDES",
    path="../data/raw/twosides"
)

print("TWOSIDES dataset object created successfully!")

Downloading...
100%|██████████| 677M/677M [01:03<00:00, 10.7MiB/s]
Loading...
Done!

TWOSIDES dataset object created successfully!

In [21]:
twosides_df = twosides_data.get_data()

print("Dataset loaded successfully!")
print("Shape:", twosides_df.shape)

Dataset loaded successfully!
Shape: (4649441, 5)

In [22]:
print("Columns:")
print(twosides_df.columns.tolist())

print("\nData types:")
print(twosides_df.dtypes)

print("\nMissing values:")
print(twosides_df.isnull().sum())

print("\nFirst 5 rows:")
display(twosides_df.head())

Columns:
['Drug1_ID', 'Drug1', 'Drug2_ID', 'Drug2', 'Y']

Data types:
Drug1_ID    object
Drug1       object
Drug2_ID    object
Drug2       object
Y            int64
dtype: object

Missing values:
Drug1_ID    0
Drug1       0
Drug2_ID    0
Drug2       0
Y           0
dtype: int64

First 5 rows:

,Drug1_ID,Drug1,Drug2_ID,Drug2,Y
0,CID000002173,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O...,CID000003345,CCC(=O)N(C1CCN(CC1)CCC2=CC=CC=C2)C3=CC=CC=C3,1024
1,CID000002173,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O...,CID000003345,CCC(=O)N(C1CCN(CC1)CCC2=CC=CC=C2)C3=CC=CC=C3,767
2,CID000002173,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O...,CID000003345,CCC(=O)N(C1CCN(CC1)CCC2=CC=CC=C2)C3=CC=CC=C3,79
3,CID000002173,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O...,CID000003345,CCC(=O)N(C1CCN(CC1)CCC2=CC=CC=C2)C3=CC=CC=C3,25
4,CID000002173,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O...,CID000003345,CCC(=O)N(C1CCN(CC1)CCC2=CC=CC=C2)C3=CC=CC=C3,85

In [23]:
print("\nUnique Y values:", twosides_df["Y"].nunique())

print("\nTop interaction/side-effect labels:")
print(twosides_df["Y"].value_counts().head(20))

Unique Y values: 1317

Top interaction/side-effect labels:
Y
464     28568
37      27006
258     26037
600     25190
692     24430
315     24260
648     23894
238     23848
74      23515
926     23043
963     21981
321     21806
154     21781
1       21410
1221    21322
153     21013
243     20204
85      19930
367     19803
444     19376
Name: count, dtype: int64

In [24]:
print("\nUnique Y labels:")
print(sorted(twosides_df["Y"].unique())[:20])

Unique Y labels:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [25]:
print(
    "Exact duplicate rows:",
    twosides_df.duplicated().sum()
)

Exact duplicate rows: 0

In [26]:
print(
    "Duplicate Drug1 + Drug2 + Y relationships:",
    twosides_df.duplicated(
        subset=["Drug1_ID", "Drug2_ID", "Y"]
    ).sum()
)

Duplicate Drug1 + Drug2 + Y relationships: 0

In [27]:
repeated_pair_rows = twosides_df.duplicated(
    subset=["Drug1_ID", "Drug2_ID"],
    keep=False
).sum()

print(
    "Rows belonging to repeated directed drug pairs:",
    repeated_pair_rows
)

Rows belonging to repeated directed drug pairs: 4649373

In [28]:
unique_directed_pairs = twosides_df[
    ["Drug1_ID", "Drug2_ID"]
].drop_duplicates()

print(
    "Unique directed drug pairs:",
    len(unique_directed_pairs)
)

Unique directed drug pairs: 63473

In [29]:
events_per_pair = (
    twosides_df
    .groupby(["Drug1_ID", "Drug2_ID"])
    .size()
)

print("Average adverse events per pair:", events_per_pair.mean())
print("Minimum:", events_per_pair.min())
print("Maximum:", events_per_pair.max())

Average adverse events per pair: 73.25068926945315
Minimum: 1
Maximum: 540

In [30]:
events_per_pair.sort_values(
    ascending=False
).head(10)

Drug1_ID      Drug2_ID
CID000003883  CID000004594    540
CID000002662  CID000003883    524
CID000004594  CID000005090    494
CID000005090  CID000005732    478
CID000002662  CID000003446    476
CID000002678  CID000004900    468
CID000003958  CID000005090    466
CID000004900  CID000005090    465
CID000002662  CID000004900    462
CID000004594  CID000004635    461
dtype: int64

In [31]:
unique_drugs = set(twosides_df["Drug1_ID"]) | set(twosides_df["Drug2_ID"])

print("Unique drugs:", len(unique_drugs))

Unique drugs: 645

In [32]:
drug1_structure_check = (
    twosides_df
    .groupby("Drug1_ID")["Drug1"]
    .nunique()
)

drug2_structure_check = (
    twosides_df
    .groupby("Drug2_ID")["Drug2"]
    .nunique()
)

print(
    "Drug1 IDs with multiple structures:",
    (drug1_structure_check > 1).sum()
)

print(
    "Drug2 IDs with multiple structures:",
    (drug2_structure_check > 1).sum()
)

Drug1 IDs with multiple structures: 0
Drug2 IDs with multiple structures: 0

In [33]:
pairs = twosides_df[
    ["Drug1_ID", "Drug2_ID"]
].drop_duplicates()

pair_set = set(
    zip(
        pairs["Drug1_ID"],
        pairs["Drug2_ID"]
    )
)

reverse_pair_count = sum(
    (drug2, drug1) in pair_set
    for drug1, drug2 in pair_set
)

print("Directed pairs having a reverse counterpart:", reverse_pair_count)
print("Total unique directed pairs:", len(pair_set))

Directed pairs having a reverse counterpart: 0
Total unique directed pairs: 63473

In [35]:
print([x for x in dir(twosides_data) if "label" in x.lower() or "map" in x.lower()])

['get_label_meaning', 'label_distribution', 'label_name']

In [40]:
print(twosides_data.get_label_meaning)
print(twosides_data.get_label_meaning(464))

<bound method DataLoader.get_label_meaning of <tdc.multi_pred.ddi.DDI object at 0x30ed17260>>

AttributeError: 'DDI' object has no attribute 'target'

In [41]:
label_meaning = twosides_data.get_label_meaning(output_format="dict")

AttributeError: 'DDI' object has no attribute 'target'

In [42]:
from pathlib import Path

twosides_path = Path("../data/raw/twosides")

for item in sorted(twosides_path.rglob("*")):
    print(item)

../data/raw/twosides/twosides.csv

In [43]:
import pandas as pd

raw_twosides = pd.read_csv("../data/raw/twosides/twosides.csv")

print("Shape:", raw_twosides.shape)
print("\nColumns:", raw_twosides.columns.tolist())

display(raw_twosides.head())

Shape: (4649441, 6)

Columns: ['ID1', 'ID2', 'Y', 'Side Effect Name', 'X1', 'X2']

,ID1,ID2,Y,Side Effect Name,X1,X2
0,CID000002173,CID000003345,1024,hypermagnesemia,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O...,CCC(=O)N(C1CCN(CC1)CCC2=CC=CC=C2)C3=CC=CC=C3
1,CID000002173,CID000003345,767,retinopathy of prematurity,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O...,CCC(=O)N(C1CCN(CC1)CCC2=CC=CC=C2)C3=CC=CC=C3
2,CID000002173,CID000003345,79,atelectasis,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O...,CCC(=O)N(C1CCN(CC1)CCC2=CC=CC=C2)C3=CC=CC=C3
3,CID000002173,CID000003345,25,alkalosis,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O...,CCC(=O)N(C1CCN(CC1)CCC2=CC=CC=C2)C3=CC=CC=C3
4,CID000002173,CID000003345,85,Back Ache,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O...,CCC(=O)N(C1CCN(CC1)CCC2=CC=CC=C2)C3=CC=CC=C3

In [44]:
print("Raw TWOSIDES shape:", raw_twosides.shape)

print("\nColumns:")
print(raw_twosides.columns.tolist())

print("\nMissing values:")
print(raw_twosides.isnull().sum())

print("\nUnique side-effect names:")
print(raw_twosides["Side Effect Name"].nunique())

print("\nUnique Y labels:")
print(raw_twosides["Y"].nunique())

Raw TWOSIDES shape: (4649441, 6)

Columns:
['ID1', 'ID2', 'Y', 'Side Effect Name', 'X1', 'X2']

Missing values:
ID1                 0
ID2                 0
Y                   0
Side Effect Name    0
X1                  0
X2                  0
dtype: int64

Unique side-effect names:
1317

Unique Y labels:
1317

In [45]:
y_to_name = (
    raw_twosides
    .groupby("Y")["Side Effect Name"]
    .nunique()
)

print(
    "Y labels mapping to more than one side-effect name:",
    (y_to_name > 1).sum()
)

Y labels mapping to more than one side-effect name: 0

In [46]:
name_to_y = (
    raw_twosides
    .groupby("Side Effect Name")["Y"]
    .nunique()
)

print(
    "Side-effect names mapping to more than one Y:",
    (name_to_y > 1).sum()
)

Side-effect names mapping to more than one Y: 0